language: node_js
node_js:
- '11.6'
sudo: required
services:
- docker
before_script:
- npm install
- npm run build
- npm run populate
script:
- npm test
- docker build -t nodeproject_web .
after_success:
- docker login -u $USER -p $PASSWORD
- docker tag nodeproject_web $USER/nodeproject_web
- docker push $USER/nodeproject_web
