language: node_js
node_js:
- '11.6'
sudo: required
services:
- docker
before_script:
- npm install
script:
- npm test
- docker build -t nodeproject_web .
after_success:
- docker login -u $USER -p $PASSWORD
- docker tag nodeproject_web $USER/nodeproject_web
- docker push $USER/nodeproject_web
deploy:
  provider: heroku
  api_key:
    secure: HnWn2YnKWZ3zlUon7cG3usiMCJjd6G5i9IN9USd6EslDQff1bZh+yTmTJGrNkXsl/bi4FD6/FO/03HaMgtsh4MX3x4tjWNoo1jnImoJa1/zfJ41l94vEpfbBscNq+6oDm6NY064aej6u8ymeodgE4yxmyMcKao5eJtqpE87oCiv3u91E5t3XcJUAmnbgJTvt32eVAbhNibNtCxfxO7uMYjYoohomJX8pF6vPWA/J2VITIZ5mW07tN+myR5RCHuh23IvcfZ1wHnxco+DmRlrnVQEByV2oFrs1Zns2RFJMh7FdhcurVZ5bPf/R7V8G9QI2YNNznNNtMusxVK6/j1C9KOd4OF5OA7n5QBg1snWEaf7g+f1N1BBy7RFQ4B6RAGFLBwFW5OF3WjNixohYtI2PbTZK+3po9AxwaO8ngN4RGFEcvDI20U+YYHE3BF5PvrqmR7n72zNuDzPsS9kD8gyLQ3iZxeBHNtdfjoybyQgjBlpAZ9QcqqY4R9Yeh3/Bv2VvxtNXI35h4we1wLmNTCppOerOODfM7MpWNRV2UeY/pB//26nVJhSN+qkE8ZDSOTC6aQ2yvtdgN7FKvX4xlR7zk1XLtglnLKB8hyUkNg2tarAuFKWKz1QFtI4ZEUnA6QPuoX+Lirn3+1BeLi1iTMi+lnxpDsNi9c3udedTwBotbVY=
  app:
    master: ecenodeproject
  on:
    repo: JProuvost/Node-Project